"""
    node.py - Defines a Node
"""

class Node():
    """
        Model for a Node. Each instance holds values of IP Address, Port, and ID
        generated by a hash function.
    """
    def __init__(self, IP_ADDRESS, PORT, ID):
        self.IP_ADDRESS = IP_ADDRESS
        self.PORT = PORT
        self.ID = ID

    def to_dict(self):
        return 'ID: {0}, IP: {1}, PORT: {2}'.format(self.ID, self.IP, self.PORT)
